model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 16
  input_size: 32
  hidden_dims: [32,64,128,256]

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 32
  batch_size: 64 # Better to have a square number
  LR: 0.005 #orig 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [0]
  #max_nb_epochs: 50
  max_epochs: 100

logging_params:
  ckpt_save_dir: "ckpts/VanillaVAE"
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265
