model_params:
  name: 'WAE_MMD'
  in_channels: 1
  latent_dim: 16
  input_size: 32
  hidden_dims: [32,64,128,256]
  reg_weight: 5000
  kernel_type: 'rbf'

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 32
  batch_size: 144 # Better to have a square number
  LR: 0.01
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [0]
  #max_nb_epochs: 50
  max_epochs: 100

logging_params:
  ckpt_save_dir: "ckpts/WAERBF"
  save_dir: "logs/"
  name: "WAERBF"
  manual_seed: 1265




