model_params:
  name: 'SWAE_3D'
  in_channels: 1
  input_size: 8
  latent_dim: 6
  reg_weight: 100
  hidden_dims: [32,64,128]
  #strides: [1,2,2,2]
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"
  #quant_mode: 1

exp_params:
  dataset: hurricane
  data_path: "/home/jliu447/lossycompression/Hurricane/clean-data-Jinyang"
  field: 'QVAPOR'
  epsilon: 1e-4
  max: 0.02368359
  min: 0
  start: 1
  end: 41 
  img_size: 8
  cache_size: 131072
  batch_size: 64 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [0,1,2,3]
  #max_nb_epochs: 50
  max_epochs: 101
logging_params: 
  ckpt_save_dir: "ckpts/SWAE_QVAPOR_8cubeto6_bs64_3264128"
  save_dir: "logs/"
  name: "SWAE_QVAPOR_8cubeto6_bs64_3264128"
  manual_seed: 1265




