model_params:
  name: 'SWAE'
  in_channels: 1
  input_size: 32
  latent_dim: 128
  reg_weight: 100
  hidden_dims: [32,64,128,256]
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"
  quant_mode: 1
  

exp_params:
  dataset: cesm_new
  data_path: "/home/jliu447/lossycompression/cesm-multisnapshot-5fields"
  field : "FREQSH"
  max: 1.0
  min: 0.0
  img_size: 32
  batch_size: 64 # Better to have a square number
  LR: 0.01
  weight_decay: 0.0
  scheduler_gamma: 0.95
  

trainer_params:
  gpus: [6]
  #max_nb_epochs: 50
  max_epochs: 101

logging_params:
  ckpt_save_dir: "ckpts/SWAE_3232_128q_FREQSH_bs64"
  save_dir: "logs/"
  name: "SWAE_3232_128q_FREQSH_bs64"
  manual_seed: 1265




