model_params:
  name: 'SWAE_3D'
  in_channels: 1
  input_size: 8
  latent_dim: 8
  reg_weight: 100
  hidden_dims: [64,128,256]
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"

exp_params:
  dataset: hurricane
  data_path: "/home/jliu447/lossycompression/Hurricane/clean-data-Jinyang"
  field: 'U'
  max: 85.17703
  min: -79.47297
  epsilon: 1e-4
  start: 1
  end: 41 
  img_size: 8
  cache_size: 131072
  batch_size: 64 # Better to have a square number
  LR: 0.01
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [0,1,2,3]
  #max_nb_epochs: 50
  max_epochs: 101
logging_params: 
  ckpt_save_dir: "ckpts_new/SWAE_U_8cubeto8_bs64_64128256_lr0.01"
  save_dir: "logs/"
  name: "SWAE_U_8cubeto8_bs64_3264128256_lr0.01"
  manual_seed: 1265




