model_params:
  name: 'SWAE'
  in_channels: 1
  input_size: 16
  latent_dim: 4
  reg_weight: 100
  hidden_dims: [16,32,64,128]
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"
  

exp_params:
  dataset: exafel
  data_path: "/home/jliu447/lossycompression/EXAFEL/extracted"
  epsilon: 1e-4
  max: 14766.948
  min: -16019.074
  img_size: 16
  batch_size: 64 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  

trainer_params:
  gpus: [4]
  #max_nb_epochs: 50
  max_epochs: 101

logging_params:
  ckpt_save_dir: "ckpts_new/SWAE_1616_4_EXAFEL_bs64"
  save_dir: "logs/"
  name: "SWAE_1616_4_EXAFEL_bs64"
  manual_seed: 1265




