model_params:
  name: 'SWAE_3D'
  in_channels: 1
  input_size: 16
  latent_dim: 16
  reg_weight: 100
  hidden_dims: [32,64,128,256]
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"
  actv: "gdn"
  norm: "no"

exp_params:
  dataset: aramco
  data_path: "/home/jliu447/lossycompression/aramco"
  start: 1400
  end: 1500 
  epsilon: 1e-4
  img_size: 16
  cache_size: 131072
  batch_size: 256 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [0,1,2,3,4,5,6,7]
  #max_nb_epochs: 50
  max_epochs: 101
logging_params: 
  ckpt_save_dir: "ckpts_gdn/aramco_16cubeto16_bs256x8_lr1e-3"
  save_dir: "logs/"
  name: "SWAE_aramcofilter_16cubeto16_bs256x8_lr1e-3"
  manual_seed: 1265




