model_params:
  name: 'SWAE_3D'
  in_channels: 1
  input_size: 8
  latent_dim: 16
  reg_weight: 100
  hidden_dims: [32,64,128]
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"
  actv: "gdn"
  norm: "no"

exp_params:
  dataset: nyx
  data_path: "/home/jliu447/lossycompression/NYX"
  field: "baryon_density"
  max: 5.06394195556640625
  min: -1.306397557258605957
  log: 1
  start: 0
  end: 4 
  epsilon: 1e-4
  img_size: 8
  cache_size: 131072
  batch_size: 64 # Better to have a square number
  LR: 0.0004
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [0,1,2,3]
  #max_nb_epochs: 50
  max_epochs: 101
logging_params: 
  ckpt_save_dir: "ckpts_gdn/bdlog_8cubeto16_bs64x4_3264128_lr4e-4"
  save_dir: "logs/"
  name: "bdlog_8cubeto16_bs64x4_3264128_lr4e-4"
  manual_seed: 1265




