model_params:
  name: 'SWAE'
  in_channels: 1
  input_size: 32
  latent_dim: 16
  reg_weight: 100
  hidden_dims: [32,64,128,256]
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"
  actv: "gdn"
  norm: "no"
  

exp_params:
  dataset: exafel
  data_path: "/home/jliu447/lossycompression/EXAFEL/extracted"
 
  max: 14766.948
  min: -16019.074
  img_size: 32
  batch_size: 64 # Better to have a square number
  LR: 0.0004
  weight_decay: 0.0
  scheduler_gamma: 0.95
  

trainer_params:
  gpus: [0,1,2,3]
  #max_nb_epochs: 50
  max_epochs: 101

logging_params:
  ckpt_save_dir: "ckpts_gdn/EXAFEL_bs64x4_lr4e-4"
  save_dir: "logs/"
  name: "EXAFEL_bs64x4_lr4e-4"
  manual_seed: 1265




