model_params:
  name: 'SWAE_3D'
  in_channels: 1
  input_size: 8
  latent_dim: 8
  reg_weight: 100
  hidden_dims: [64,256,512]
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"

exp_params:
  dataset: aramco
  data_path: "/home/jliu447/lossycompression/aramco"
  start: 1400
  end: 1500 
  epsilon: 1e-4
  img_size: 8
  cache_size: 131072
  batch_size: 256 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [7]
  #max_nb_epochs: 50
  max_epochs: 101
logging_params: 
  ckpt_save_dir: "ckpts_new/SWAE_aramco_8cubeto8_bs256_64256512"
  save_dir: "logs/"
  name: "SWAE_aramco_8cubeto8_bs256_64256512"
  manual_seed: 1265




