model_params:
  name: 'VanillaAE'
  in_channels: 1
  
  input_size: 16
  latent_dim: 4
  
  hidden_dims: [32,64,128,256]
  

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 16
  batch_size: 64 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [4,5]
  #max_nb_epochs: 50
  max_epochs: 101

logging_params:
  ckpt_save_dir: "ckpts/AE/"
  save_dir: "logs/"
  name: "AE"
  manual_seed: 1265
