model_params:
  name: 'BetaVAE'
  in_channels: 1
  latent_dim: 4
  loss_type: 'H'
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 16
  batch_size: 64 # Better to have a square number
  LR: 0.001 #orig 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [0]
  #max_nb_epochs: 50
  max_epochs: 50
  

logging_params:
  ckpt_save_dir: "ckpts/BetaVAE_H"
  save_dir: "logs/"
  name: "BetaVAE_H"
  manual_seed: 1265
