model_params:
  name: 'SWAE'
  in_channels: 1
  input_size: 32
  latent_dim: 16
  reg_weight: 10
  hidden_dims: [32,64,128,256]
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"
  actv: "gdn"
  norm: "no"
  

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 32
  batch_size: 256 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [0]
  #max_nb_epochs: 50
  max_epochs: 101

logging_params:
  ckpt_save_dir: "ckpts_test/CLDHGH_32_16_gdn_lr1e-3"
  save_dir: "logs/"
  name: "CLDHGH_32_16_gdn_lr1e-3"
  manual_seed: 1265




