model_params:
  name: 'DIPVAE'
  in_channels: 1
  latent_dim: 128
  lambda_diag: 0.05
  lambda_offdiag: 0.1


exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.97

trainer_params:
  gpus: [1]
  #max_nb_epochs: 50
  max_epochs: 101
  

logging_params:
  ckpt_save_dir: "ckpts/DIPVAE128"
  save_dir: "logs/"
  name: "DIPVAE"
  manual_seed: 1265
