model_params:
  name: 'InfoVAE'
  in_channels: 1
  latent_dim: 64
  reg_weight: 110  # MMD weight
  kernel_type: 'imq'
  alpha: -9.0     # KLD weight
  beta: 10.5      # Reconstruction weight

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [4]
  #max_nb_epochs: 50
  max_epochs: 100
  gradient_clip_val: 0.8


logging_params:
  ckpt_save_dir: "ckpts/InfoVAE"
  save_dir: "logs/"
  name: "InfoVAE"
  manual_seed: 1265




