model_params:
  name: 'IWAE'
  in_channels: 1
  latent_dim: 64
  num_samples: 5

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.007
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [5]
  
  max_epochs: 100
  

logging_params:
  ckpt_save_dir: "ckpts/IWAE"
  save_dir: "logs/"
  name: "IWAE"
  manual_seed: 1265
