model_params:
  name: 'MIWAE'
  in_channels: 1
  latent_dim: 64
  num_samples: 5
  num_estimates: 3

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [7]
  #max_nb_epochs: 50
  max_epochs: 100
  save_dir: "ckpts/MIWAE"

logging_params:
  save_dir: "logs/"
  name: "MIWAE"
  manual_seed: 1265
