model_params:
  name: 'SWAE'
  in_channels: 1
  input_size: 16
  latent_dim: 4
  reg_weight: 100
  hidden_dims: [16,32,64,128]
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"
  

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 16
  batch_size: 64 # Better to have a square number
  LR: 0.01
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [0]
  #max_nb_epochs: 50
  max_epochs: 50
logging_params:
  ckpt_save_dir: "ckpts_new/SWAE4"
  save_dir: "logs/"
  name: "SWAE"
  manual_seed: 1265




