model_params:
  name: 'SWAE'
  in_channels: 1
  input_size: 16
  latent_dim: 4
  reg_weight: 100
  hidden_dims: [32,64,128,256]
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 16
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [2]
  #max_nb_epochs: 50
  max_epochs: 101

logging_params:
  ckpt_save_dir: "ckpts/SWAE_1616_4_doublelayer_bs144_3264128256"
  save_dir: "logs/"
  name: "SWAE_1616_4_doublelayer_bs144_3264128256"
  manual_seed: 1265




