model_params:
  name: 'SWAE'
  in_channels: 1
  input_size: 32
  latent_dim: 16
  reg_weight: 50
  hidden_dims: [32,64,128,256]
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"
  

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 32
  batch_size: 64 # Better to have a square number
  LR: 0.01
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [0,1,2,3]
  #max_nb_epochs: 50
  max_epochs: 101

logging_params:
  ckpt_save_dir: "ckpts_new/SWAE_3232_16_doublelayer_bs64_reg50"
  save_dir: "logs/"
  name: "SWAE_3232_16_doublelayer_bs64_reg50"
  manual_seed: 1265




