model_params:
  name: 'SWAE_EXPAND'
  in_channels: 1
  latent_dim: 128
  reg_weight: 100
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"
  pretrained_layers: "/home/jliu447/lossycompression/PyTorch-VAE/ckpts/SWAE128/last.ckpt"

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [4]
  #max_nb_epochs: 50
  max_epochs: 101

logging_params:
  ckpt_save_dir: "ckpts/SWAEexpand"
  save_dir: "logs/"
  name: "SWAEexpand"
  manual_seed: 1265




