model_params:
  name: 'SWAE'
  in_channels: 1
  input_size: 16
  latent_dim: 4
  reg_weight: 100
  hidden_dims: [4,8,8,4]
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"
  use_fc: False

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 16
  batch_size: 64 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [0,1,2,3]
  #max_nb_epochs: 50
  max_epochs: 101

logging_params:
  ckpt_save_dir: "ckpts_new/SWAE_1616_4_doublelayer_nfc_bs64_4884"
  save_dir: "logs/"
  name: "SWAE_1616_4_doublelayer_nfc_bs64_4884"
  manual_seed: 1265




