model_params:
  name: 'SWAE'
  in_channels: 1
  input_size: 32
  latent_dim: 16
  reg_weight: 100
  hidden_dims: [64,128,256,256]
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"
  struct: 'resnet'
  encoder_final_layer: 'fc'
  actv: 'leakyrelu'
  resblock_num: [2,2,2,2]
  first_channel: 64
  resnet_pooling: True
  resnet_fc: True
exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 32
  batch_size: 144 # Better to have a square number
  LR: 0.01
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [0]
  #max_nb_epochs: 50
  max_epochs: 101

logging_params:
  ckpt_save_dir: "ckpts_new/SWAE_3232_16_resnet_bs144"
  save_dir: "logs/"
  name: "SWAE_3232_16_resnet_bs144"
  manual_seed: 1265




