model_params:
  name: 'VampVAE'
  in_channels: 1
  latent_dim: 64

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [7]
  #max_nb_epochs: 50
  max_epochs: 101

logging_params:
  ckpt_save_dir: "ckpts/VampVAE"
  save_dir: "logs/"
  name: "VampVAE"
  manual_seed: 1265
