model_params:
  name: 'VQVAE'
  in_channels: 1
  embedding_dim: 32
  num_embeddings: 8
  img_size: 16
  beta: 0.25

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 16
  batch_size: 64 # Better to have a square number
  LR: 0.002 #orig 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.0

trainer_params:
  gpus: [0]
 
  max_epochs: 50

logging_params:
  save_dir: "logs/VQVAE"
  name: "VQVAE"
  manual_seed: 1265
