model_params:
  name: 'WAE_MMD'
  in_channels: 1
  input_size: 16
  latent_dim: 4
  hidden_dims: [32,64,128,256]
  reg_weight: 5000
  kernel_type: 'rbf'

exp_params:
  dataset: cesm
  data_path: "/home/jliu447/lossycompression/multisnapshot-data-cleaned/CLDHGH"
  img_size: 16
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [7]
  #max_nb_epochs: 50
  max_epochs: 101

logging_params:
  ckpt_save_dir: "ckpts/WassersteinVAE_RBF16164_doublelayer_3264128256"
  save_dir: "logs/"
  name: "WassersteinVAE_RBF16164_doublelayer_3264128256"
  manual_seed: 1265




